import os
configfile: "config.yaml"

# do onstart/onexit things
sample_schemas = ['sample', 'assembly', 'strandedness', 'condition']
config_schemas = ['general', 'download']
include: "../../rules/configuration.smk"


# load the relevant rules
include: f"{config['rule_dir']}/pananse.smk"

rule run_all:
    """
    call peaks for each sample (or condition if applies)
    """
    input:
        expand(["{result_dir}/enhancer/{assemblies}-{sample}.bed"],
                **{**config, 
                    **{'assemblies': set(samples['assembly']), 'sample': set(samples.index)}})
